apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1 # Default organization
    url: http://influxdb:8086
    isDefault: true
    user: dev
    database: iot
    secureJsonData:
      password: "dev"
    jsonData:
      httpMethod: GET
      sslmode: "disable"
    version: 1
    editable: true